<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/1/12
 * Time: 11:12
 */

define('NAME','name');
//节点表常量定义
define('SQL_NODEID','nodeid');
define('SQL_IDMODEL','idmodel');
define('SQL_PARENTID','parentid');
define('SQL_PARENTPATH','parentpath');
define('SQL_IDROOT','idroot');
define('SQL_LEVEL','level');
define('SQL_CHILD','child');
define('SQL_ARRCHILDID','arrchildid');
define('SQL_IDORDER','idorder');
define('SQL_NODEDIR','nodedir');
define('SQL_PARENTDIR','parentdir');
define('SQL_NODEPICURL','nodepicurl');
define('SQL_SHOWONMENU','showonmenu');
define('SQL_SHOWONPATH','showonpath');
define('SQL_IDONEPAGE','isonepage');
define('SQL_ITEMPAGESIZE','itempagesize');
define('SQL_OPTION','option');
define('SQL_LINKURL','linkurl');
define('SQL_TEMPLATEOFNODEINDEX','templateofnodeindex');
define('SQL_TEMPLATEOFNODELIST','templateofnodelist');
define('SQL_TEMPLATEOFNODECONTENT','templateofnodecontent');
define('SQL_SQL_IDSITE','idsite');
define('SQL_NODETYPE','nodetype');
define('SQL_COMMENTMODEL','commentmodel');
define('SQL_NODE_NAME','nodename');
define('SQL_MODEL_NAME','modelname');
define('SQL_TIPS','tips');
define('SQL_REMARK','remark');
define('SQL_METAKEYWORDS','metakeywords');
define('SQL_METAREMARK','metaremark');

//内容表常量定义
define('SQL_CONTENTID','contentid');
define('SQL_USERID','userid');
define('SQL_CREATETIME','createtime');
define('SQL_MODELID','modelid');
define('SQL_CONTENTTYPE','contenttype');
define('SQL_PICURL','picurl');
define('SQL_DATELASTMODIFIED','datelastmodified');
define('SQL_TEMPLATEFILE','templatefile');
define('SQL_HITS','hits');
define('SQL_STATUS','status');
define('SQL_FILENAME','filename');
define('SQL_SITEID','siteid');
define('SQL_CONTENTTYPETEXT','contenttypetext');
define('SQL_STATUSTEXT','statustext');
define('SQL_INDEXOF','indexof');
define('SQL_TITLE','title');
define('SQL_SUBTITLE','subtitle');
define('SQL_SUMMARY','summary');
define('SQL_KEYWORD','keyword');
define('SQL_AUTHOR','author');
define('SQL_EDITOR','editor');
define('SQL_SOURCE','source');
define('SQL_CONTENT','content');
define('SQL_INPUTER','inputer');
define('SQL_METADASCRIPTION','metadescription');
define('SQL_FIELDNUM1','fieldnum1');
define('SQL_FIELDNUM2','fieldnum2');
define('SQL_FIELDNUM3','fieldnum3');
define('SQL_FIELDNUM4','fieldnum4');
define('SQL_FIELDNUM5','fieldnum5');
define('SQL_FIELDDATE1','fielddate1');
define('SQL_FIELDDATE2','fielddate2');
define('SQL_FIELDDATE3','fielddate3');
define('SQL_FIELDDATE4','fielddate4');
define('SQL_FIELDDATE5','fielddate5');
define('SQL_FIELDSPARE1','fieldspare1');
define('SQL_FIELDSPARE2','fieldspare2');
define('SQL_FIELDSPARE3','fieldspare3');
define('SQL_FIELDSPARE4','fieldspare4');
define('SQL_FIELDSPARE5','fieldspare5');
define('SQL_FIELDSPARE6','fieldspare6');
define('SQL_FIELDSPARE7','fieldspare7');
define('SQL_FIELDSPARE8','fieldspare8');
define('SQL_FIELDSPARE9','fieldspare9');
define('SQL_FIELDSPARE10','fieldspare10');
define('SQL_FIELDSPARE11','fieldspare11');
define('SQL_FIELDSPARE12','fieldspare12');
define('SQL_FIELDSPARE13','fieldspare13');
define('SQL_FIELDSPARE14','fieldspare14');
define('SQL_FIELDSPARE15','fieldspare15');

//评论表
define('SQL_COMMENTID','commentid');
define('SQL_IDUSER','iduser');
define('SQL_CHRACCOUNT','chraccount');
define('SQL_CHRPWD','chrpwd');
define('SQL_INTLEVEL','intlevel');
define('SQL_CHRNAME','chrname');
define('SQL_INTSEX','intsex');
define('SQL_DTBIRTHDAY','dtbirthday');
define('SQL_INTPROVINCE','intprovince');
define('SQL_INTCITY','intcity');
define('SQL_INTAREA','intarea');
define('SQL_CHRADDRESS','chraddress');
define('SQL_CHRPOSTCODE','chrpostcode');
define('SQL_CHRTEL','chrtel');
define('SQL_DTKEYTIME','dtkeytime');
define('SQL_ADDTIME','addtime');
define('SQL_CHRKEY','chrkey');
define('SQL_CHRMAIL','chrmail');
define('SQL_CHRREMARK','chrremark');
define('SQL_INTSTATE','intstate');
define('SQL_INTLOCK','intlock');

//字典表
define('SQL_ID','id');
define('SQL_BOOKCODE','bookcode');
define('SQL_CODE','code');
define('SQL_NAME','name');
define('SQL_ORDER','order');
define('SQL_PARENTCODE','parentcode');
define('SQL_NEXTLEVEL','nextlevel');


//网站配置表 config_rule 表
define('IDMENU','idmenu');
define('CHRNAME','chrname');
define('FIELDNAME','fieldname');
define('FIELDTYPE','fieldtype');
define('INTSN','intsn');
define('ISSHOW','isshow');
define('INTFLAG','intflag');
define('TIPS','tips');
define('REMARK','remark');
define('DEFAULTVAL','defaultval');
define('TXTWIDTH','txtwidth');
define('TXTHEIGHT','txtheight');
define('MAXLENGTH','maxlength');
define('TYPE','type');
define('TXTTYPE','txttype');
define('SETTINGS','settings');
define('CHILDSETTING','childsetting');


//广告表
define('SQL_ADID','adid');
define('SQL_PID','pid');
define('SQL_MEDIATYPE','media_type');
define('SQL_ADNAME','ad_name');
define('SQL_ADLINK','ad_link');
define('SQL_ADCODE','ad_code');
define('SQL_STARTTIME','start_time');
define('SQL_ENDTIME','end_time');
define('SQL_LINKMAN','link_man');
define('SQL_LINKEMAIL','link_email');
define('SQL_LINKPHONE','link_phone');
define('SQL_CLICKCOUNT','click_count');
define('SQL_ENABLED','enabled');
define('SQL_ORDERBY','orderby');
define('SQL_TARGET','target');


