<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/1/12
 * Time: 11:13
 */

define('NAME','en_name');
//节点表常量定义
define('SQL_NODEID','nodeid');
define('SQL_IDMODEL','idmodel');
define('SQL_PARENTID','parentid');
define('SQL_PARENTPATH','parentpath');
define('SQL_IDROOT','idroot');
define('SQL_LEVEL','level');
define('SQL_CHILD','child');
define('SQL_ARRCHILDID','arrchildid');
define('SQL_IDORDER','idorder');
define('SQL_NODEDIR','nodedir');
define('SQL_PARENTDIR','parentdir');
define('SQL_NODEPICURL','nodepicurl');
define('SQL_SHOWONMENU','showonmenu');
define('SQL_SHOWONPATH','showonpath');
define('SQL_IDONEPAGE','isonepage');
define('SQL_ITEMPAGESIZE','itempagesize');
define('SQL_OPTION','option');
define('SQL_LINKURL','linkurl');
define('SQL_TEMPLATEOFNODEINDEX','templateofnodeindex');
define('SQL_TEMPLATEOFNODELIST','templateofnodelist');
define('SQL_TEMPLATEOFNODECONTENT','templateofnodecontent');
define('SQL_SQL_IDSITE','idsite');
define('SQL_NODETYPE','nodetype');
define('SQL_COMMENTMODEL','commentmodel');
define('SQL_NODE_NAME','en_nodename');
define('SQL_MODEL_NAME','en_modelname');
define('SQL_TIPS','en_tips');
define('SQL_REMARK','en_remark');
define('SQL_METAKEYWORDS','en_metakeywords');
define('SQL_METAREMARK','en_metaremark');

//内容表常量定义
define('SQL_CONTENTID','contentid');
define('SQL_USERID','userid');
define('SQL_CREATETIME','createtime');
define('SQL_MODELID','modelid');
define('SQL_CONTENTTYPE','contenttype');
define('SQL_PICURL','picurl');
define('SQL_DATELASTMODIFIED','datelastmodified');
define('SQL_TEMPLATEFILE','templatefile');
define('SQL_HITS','hits');
define('SQL_STATUS','status');
define('SQL_FILENAME','filename');
define('SQL_SITEID','siteid');
define('SQL_CONTENTTYPETEXT','contenttypetext');
define('SQL_STATUSTEXT','statustext');
define('SQL_INDEXOF','indexof');
define('SQL_TITLE','en_title');
define('SQL_SUBTITLE','en_subtitle');
define('SQL_SUMMARY','en_summary');
define('SQL_KEYWORD','en_keyword');
define('SQL_AUTHOR','en_author');
define('SQL_EDITOR','en_editor');
define('SQL_SOURCE','en_source');
define('SQL_CONTENT','en_content');
define('SQL_INPUTER','en_inputer');
define('SQL_METADASCRIPTION','en_metadescription');
define('SQL_FIELDNUM1','fieldnum1');
define('SQL_FIELDNUM2','fieldnum2');
define('SQL_FIELDNUM3','fieldnum3');
define('SQL_FIELDNUM4','fieldnum4');
define('SQL_FIELDNUM5','fieldnum5');
define('SQL_FIELDDATE1','fielddate1');
define('SQL_FIELDDATE2','fielddate2');
define('SQL_FIELDDATE3','fielddate3');
define('SQL_FIELDDATE4','fielddate4');
define('SQL_FIELDDATE5','fielddate5');
define('SQL_FIELDSPARE1','en_fieldspare1');
define('SQL_FIELDSPARE2','en_fieldspare2');
define('SQL_FIELDSPARE3','en_fieldspare3');
define('SQL_FIELDSPARE4','en_fieldspare4');
define('SQL_FIELDSPARE5','en_fieldspare5');
define('SQL_FIELDSPARE6','en_fieldspare6');
define('SQL_FIELDSPARE7','en_fieldspare7');
define('SQL_FIELDSPARE8','en_fieldspare8');
define('SQL_FIELDSPARE9','en_fieldspare9');
define('SQL_FIELDSPARE10','en_fieldspare10');
define('SQL_FIELDSPARE11','en_fieldspare11');
define('SQL_FIELDSPARE12','en_fieldspare12');
define('SQL_FIELDSPARE13','en_fieldspare13');
define('SQL_FIELDSPARE14','en_fieldspare14');
define('SQL_FIELDSPARE15','en_fieldspare15');

//评论表
define('SQL_COMMENTID','commentid');
define('SQL_IDUSER','iduser');
define('SQL_CHRACCOUNT','chraccount');
define('SQL_CHRPWD','chrpwd');
define('SQL_INTLEVEL','intlevel');
define('SQL_CHRNAME','chrname');
define('SQL_INTSEX','intsex');
define('SQL_DTBIRTHDAY','dtbirthday');
define('SQL_INTPROVINCE','intprovince');
define('SQL_INTCITY','intcity');
define('SQL_INTAREA','intarea');
define('SQL_CHRADDRESS','chraddress');
define('SQL_CHRPOSTCODE','chrpostcode');
define('SQL_CHRTEL','chrtel');
define('SQL_DTKEYTIME','dtkeytime');
define('SQL_ADDTIME','addtime');
define('SQL_CHRKEY','chrkey');
define('SQL_CHRMAIL','chrmail');
define('SQL_CHRREMARK','chrremark');
define('SQL_INTSTATE','intstate');
define('SQL_INTLOCK','intlock');

//字典表
define('SQL_ID','id');
define('SQL_BOOKCODE','bookcode');
define('SQL_CODE','code');
define('SQL_NAME','en_name');
define('SQL_ORDER','order');
define('SQL_PARENTCODE','parentcode');
define('SQL_NEXTLEVEL','nextlevel');

//网站配置表 config_rule 表
define('IDMENU','idmenu');
define('CHRNAME','en_chrname');
define('FIELDNAME','fieldname');
define('FIELDTYPE','fieldtype');
define('INTSN','intsn');
define('ISSHOW','isshow');
define('INTFLAG','intflag');
define('TIPS','en_tips');
define('REMARK','en_remark');
define('DEFAULTVAL','en_defaultval');
define('TXTWIDTH','txtwidth');
define('TXTHEIGHT','txtheight');
define('MAXLENGTH','maxlength');
define('TYPE','type');
define('TXTTYPE','txttype');
define('SETTINGS','settings');
define('CHILDSETTING','childsetting');

//广告表
define('SQL_ADID','adid');
define('SQL_PID','pid');
define('SQL_MEDIATYPE','media_type');
define('SQL_ADNAME','en_ad_name');
define('SQL_ADLINK','ad_link');
define('SQL_ADCODE','ad_code');
define('SQL_STARTTIME','start_time');
define('SQL_ENDTIME','end_time');
define('SQL_LINKMAN','en_link_man');
define('SQL_LINKEMAIL','link_email');
define('SQL_LINKPHONE','link_phone');
define('SQL_CLICKCOUNT','click_count');
define('SQL_ENABLED','enabled');
define('SQL_ORDERBY','orderby');
define('SQL_TARGET','target');

